# Generated by Django 4.0.3 on 2024-03-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_technician_employee_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('date_time',)},
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('employee_id',)},
        ),
    ]
