# Generated by Django 4.0.3 on 2024-03-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_options_alter_technician_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
